# Generated by Django 2.2.5 on 2019-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
